services:
  reverse-proxy:
    image: traefik:3
    restart: unless-stopped
    ports:
      - { published: 80,   target: 80   }
      - { published: 443,  target: 443  }
      - { published: 8080, target: 8080 }
    volumes:
      - { type: bind, source: ./etc/traefik,        target: /etc/traefik }
      - { type: bind, source: /var/run/docker.sock, target: /var/run/docker.sock }
    networks:
      traefik:

networks:
  traefik:
    name: traefik
